site_name: demo-python-project-backstage Documentation
repo_name: lucasmelin/demo123
repo_url: https://github.com/lucasmelin/demo123
edit_uri: edit/master/docs
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      accent: indigo
      toggle:
        icon: material/toggle-switch-on-outline
        name: Switch to light mode
  features:
    - navigation.top
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - meta
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed

plugins:
  - search
